### ISSUE TITLE
HEAR results

### ISSUE THREAD

**Issue by RicherMans** [gzhu06/Cacophony#1]
Hey guys,
Thanks for the good work. I am just curious about the results on HEAR. Would it be possible for you to provide your results as a Table of some sort such that one can directly "copy"/cite the results?
Currently, Figure 6 is a bit unclear in that regards since I can only "guess" the values of Cacophony.
Kind regards,
Heinrich

**Comment by gzhu06** [comment]
Hi Heinrich, sure, I'll post a more formal table on HEAR benchmark comparison in the README file very soon.

**Comment by RicherMans** [comment]
Thanks Ge Zhu!
