### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by iveshenry18** [gzhu06/Cacophony#2]
Hi, great to see the exciting results in your paper! I see that you mention sharing the pre-trained models for both the AudioMAE and Cacophony, but it looks like the links are currently just placeholders. Any ETA on those weights?

Thanks for all the great work, and let me know if there's any way I can lend a hand!

**Comment by gzhu06** [comment]
Thanks for the kind words! The Cacophony weights is shared, also I'm verifying the AudioMAE weights from the 1st stage.

**Comment by iveshenry18** [comment]
Awesome, thank you so much!
